// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsj1VwjG2Th_migz9PWIiqgm87cHr_CA8',
    appId: '1:310102548987:web:3ddb8750f6a0cfc02b6b5e',
    messagingSenderId: '310102548987',
    projectId: 'miappempleados-prueba1',
    authDomain: 'miappempleados-prueba1.firebaseapp.com',
    storageBucket: 'miappempleados-prueba1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEQJzCpyQAwFYbXqEaBA5AtVzubVu2XJA',
    appId: '1:310102548987:android:3331369ac648c7042b6b5e',
    messagingSenderId: '310102548987',
    projectId: 'miappempleados-prueba1',
    storageBucket: 'miappempleados-prueba1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4qSVZNYufPaSxg1YQg8s5bt9LgamUOuM',
    appId: '1:310102548987:ios:0b552f8710088e692b6b5e',
    messagingSenderId: '310102548987',
    projectId: 'miappempleados-prueba1',
    storageBucket: 'miappempleados-prueba1.appspot.com',
    iosBundleId: 'com.example.clase184',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4qSVZNYufPaSxg1YQg8s5bt9LgamUOuM',
    appId: '1:310102548987:ios:0b552f8710088e692b6b5e',
    messagingSenderId: '310102548987',
    projectId: 'miappempleados-prueba1',
    storageBucket: 'miappempleados-prueba1.appspot.com',
    iosBundleId: 'com.example.clase184',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBsj1VwjG2Th_migz9PWIiqgm87cHr_CA8',
    appId: '1:310102548987:web:d2564fe04f9f10902b6b5e',
    messagingSenderId: '310102548987',
    projectId: 'miappempleados-prueba1',
    authDomain: 'miappempleados-prueba1.firebaseapp.com',
    storageBucket: 'miappempleados-prueba1.appspot.com',
  );
}
